"""initialize database

Revision ID: 6057771f8063
Revises: 
Create Date: 2025-07-11 15:31:54.825432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6057771f8063'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('encrypted_access_token', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.LargeBinary(), nullable=True),
    sa.Column('spotify_username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('spotify_profile_image', sa.String(), nullable=True),
    sa.Column('spotify_display_name', sa.String(), nullable=True),
    sa.Column('spotify_country', sa.String(), nullable=True),
    sa.Column('spotify_followers', sa.Integer(), nullable=True),
    sa.Column('spotify_product', sa.String(), nullable=True),
    sa.Column('profile_updated_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_reorder_style', sa.String(), nullable=True),
    sa.Column('favorite_styles', sa.JSON(), nullable=True),
    sa.Column('user_preferences', sa.JSON(), nullable=True),
    sa.Column('subscription_tier', sa.String(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('monthly_reorders_used', sa.Integer(), nullable=True),
    sa.Column('monthly_reset_date', sa.DateTime(), nullable=True),
    sa.Column('total_reorders', sa.Integer(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
