"""remove paid & admin features

Revision ID: 6148afff5e94
Revises: cd5ac835cfca
Create Date: 2025-07-19 11:00:33.736664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6148afff5e94'
down_revision: Union[str, None] = 'cd5ac835cfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_reset_date')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'monthly_reorders_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monthly_reorders_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('subscription_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('subscription_tier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('monthly_reset_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
