"""reorder jobs

Revision ID: cd5ac835cfca
Revises: 6057771f8063
Create Date: 2025-07-12 08:44:48.874380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5ac835cfca'
down_revision: Union[str, None] = '6057771f8063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reorder_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('playlist_id', sa.String(), nullable=False),
    sa.Column('playlist_name', sa.String(), nullable=True),
    sa.Column('reorder_style', sa.String(), nullable=False),
    sa.Column('user_intent', sa.Text(), nullable=True),
    sa.Column('personal_tone', sa.Text(), nullable=True),
    sa.Column('reorder_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_tracks', sa.Integer(), nullable=True),
    sa.Column('processed_tracks', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('strategy_info', sa.Text(), nullable=True),
    sa.Column('tracks_reordered', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reorder_jobs')
    # ### end Alembic commands ###
